### ISSUE TITLE
[BUG] CohereClient uses outdated withMetrics signature and breaks compilation (post #512)

### ISSUE THREAD

**Issue by gudiwadasruthi** [llm4s/llm4s#656]
### Description

After rebasing onto current upstream/main (commit c0d9afa),
the project fails to compile due to CohereClient still using the
pre-#512 withMetrics signature.

Issue #512 updated the withMetrics contract to:

withMetrics(
  provider: String,
  model: String,
  operation: => Result[A],
  extractUsage: A => Option[TokenUsage],
  extractCost: A => Option[Double]
)

However, the recently merged CohereClient still uses the old curried
form:

withMetrics("cohere", config.model) { ... } (
  extractUsage = _.usage,
  estimateCost = ...
)

This results in compilation failure on main.

### Steps to Reproduce

1. Checkout current upstream main:
   git checkout upstream/main

2. Run:
   sbt core/compile

3. Observe compilation errors in CohereClient.scala

### Expected Behavior

Project should compile successfully on upstream/main.
All providers should comply with the updated withMetrics signature introduced in #512.

### Actual Behavior

Compilation fails with errors such as:

not enough arguments for method withMetrics
Unspecified value parameter operation
not found: value extractUsage
not found: value estimateCost

<img width="1893" height="739" alt="Image" src="https://github.com/user-attachments/assets/2235bbc2-c62d-4e7d-8a91-cea684e2bbe1" />

### Impact Areas

- [x] API / Compatibility
- [ ] Security / Privacy
- [x] Reliability / Availability
- [ ] Performance
- [ ] Documentation
- [ ] Unsure

### Error Logs / Stack Trace

```scala
D:\llm4s-feature\llm4s\modules\core\src\main\scala\org\llm4s\llmconnect\provider\CohereClient.scala:41:38:
not enough arguments for method withMetrics
Unspecified value parameter operation.

not found: value extractUsage
not found: value estimateCost
```

### Scala Version

3.7.1

### JDK Version

JDK 21

### Operating System

Windows

### LLM Provider

Ollama (local)

### Model Information

ollama/mistral

### LLM4S Version

Current main (commit c0d9afa)

### Code Snippet

```scala

```

### Configuration (if relevant)

```bash

```

### Additional Context

This appears to be a regression introduced after merging Cohere
following #512.

Other providers were updated to the new withMetrics signature,
but CohereClient was not updated accordingly.

I am preparing a minimal PR to restore compilation and bring
CohereClient into compliance with #512.

### Pre-submission Checklist

- [x] I have searched existing issues and found no duplicates
- [x] I have provided all required environment information
- [x] I have provided a minimal reproducible example
- [x] I have anonymized any sensitive data (API keys, etc.)
