### ISSUE TITLE
[ENHANCEMENT] CohereClient does not implement updated withMetrics signature and cost tracking (post #512)

### ISSUE THREAD

**Issue by gudiwadasruthi** [llm4s/llm4s#655]
### Current Behavior

Context

Issue #512 updated provider-level cost exposure and standardized the withMetrics signature:

withMetrics(
  provider: String,
  model: String,
  operation: => Result[A],
  extractUsage: A => Option[TokenUsage],
  extractCost: A => Option[Double]
)

The recently merged CohereClient (commit 38265f5) still uses the older withMetrics contract and does not properly integrate usage/cost extraction.

This causes compilation failures after rebasing onto current main.

What needs to be done

- Update CohereClient to use the new withMetrics signature.
- Provide explicit extractUsage and extractCost lambdas.
- Ensure estimatedCost is propagated to Completion.
- Ensure reasoning token pricing (if applicable) is supported.
- Add minimal provider-level test if required.
- Confirm sbt +test passes.

This is a provider-level compliance fix for #512 and should be handled separately from #513 (agent-level aggregation).

### Proposed Improvement

# ✅ Proposed Improvement

```markdown
Update `CohereClient` to align with the standardized provider metrics contract introduced in #512.
```
Proposed changes:

- Update `withMetrics` invocation to use the new explicit parameter signature.
- Provide typed lambdas:
  - `extractUsage = (c: Completion) => c.usage`
  - `extractCost = (c: Completion) => c.estimatedCost`
- Ensure `Completion.estimatedCost` is correctly populated.
- Ensure reasoning token pricing (if supported by Cohere) is respected via `CostEstimator`.
- Confirm `sbt +test` passes after the update.

## Benefits

- Restores compilation consistency across providers.
- Ensures Cohere participates in standardized usage/cost tracking.
- Prevents drift between providers.
- Enables agent-level cost aggregation (#513) to function uniformly across all providers.
- Maintains architectural consistency in the LLMConnect layer.

## Who benefits?

- Contributors working on observability and billing.
- Users tracking token usage and cost across providers.
- Future provider implementations that follow the standardized pattern.

### Impact Areas

- [x] API / Compatibility
- [x] Security / Privacy
- [ ] Reliability / Availability
- [ ] Performance
- [ ] Documentation
- [ ] Unsure

### Implementation Approach (if known)

Minimal provider-level compliance fix.

- Mirror implementation pattern used in OpenAIClient / GeminiClient.
- Do not modify cost-estimation logic.
- Do not expand scope beyond CohereClient.
- Keep PR small and isolated.

### Impact Scope

Observability

### Breaking Changes

No - Backward compatible

### Related Issues or PRs

relates to #512 and #513 

### Implementation Willingness

- [x] I would like to implement this enhancement myself
- [ ] I would be open to collaborating on implementation
- [ ] I would prefer someone else to implement this

### Pre-submission Checklist

- [x] I have searched existing issues and found no duplicates
- [x] I have clearly described the current behavior
- [x] I have explained the proposed improvement
- [x] I have identified the benefits and impact
