### PR TITLE
Add agent-level usage and cost accumulation to AgentState

### LINKED ISSUE #513: Cost Tracking: Add usage/cost accumulation to AgentState
## Context

Parent issue: #15

`AgentState` tracks conversation, tools, status, and logs — but has zero usage or cost data. An agent run that makes 5 LLM calls across tool loops has no way to report total tokens consumed or total cost.

## What to do

Add a `UsageSummary` to `AgentState` that accumulates across agent loop iterations.

### Proposed types

```scala
case class ModelUsage(
  inputTokens: Int = 0,
  outputTokens: Int = 0,
  thinkingTokens: Int = 0,
  requestCount: Int = 0,
  estimatedCostUsd: Double = 0.0
)

case class UsageSummary(
  totalInputTokens: Int = 0,
  totalOutputTokens: Int = 0,
  totalThinkingTokens: Int = 0,
  totalEstimatedCostUsd: Double = 0.0,
  requestCount: Int = 0,
  byModel: Map[String, ModelUsage] = Map.empty
) {
  def add(model: String, usage: TokenUsage, cost: Option[Double]): UsageSummary = ...
}
```

### Files to change

| File | Change |
|------|--------|
| New type file or in `AgentState.scala` | `UsageSummary` and `ModelUsage` case classes |
| `AgentState.scala` | Add `usageSummary: UsageSummary` field |
| `Agent.scala` | After each `client.complete()` call in the agent loop, accumulate usage from `Completion.usage` and `Completion.estimatedCost` into state |
| `AgentState` serialization (`toJson`/`fromJson`) | Include usage summary |
| `AgentEvent.scala` | Consider adding `UsageUpdated` event for streaming |

### Dependencies

- Depends on `Completion.estimatedCost` field (sibling issue for cost in Completion)

## Acceptance criteria

- [ ] `AgentState` carries a `UsageSummary` field
- [ ] After `agent.run(...)`, `state.usageSummary` reflects total tokens and cost across all LLM calls
- [ ] Multi-step tool-calling agents accumulate correctly (not just single-call)
- [ ] `continueConversation` carries forward accumulated usage
- [ ] Usage summary is included in `AgentState.toJson` serialization
- [ ] Handoff agents accumulate usage from sub-agents
- [ ] `sbt +test` passes

### PR DESCRIPTION
**Pull request by gudiwadasruthi**
## What does this PR do?

This PR adds **agent-level usage and cost aggregation** by extending `AgentState` with a `UsageSummary`.  
It allows users to observe total token consumption and estimated cost across **multi-step agent runs**, including tool loops, streaming, continuation, and handoff agents.

This builds on the per-request cost surfaced in `Completion` (from #512) and keeps all changes **immutable, backward-compatible, and opt-in**.

---

## Related issue

Fixes #513  
Relates to #512 (cost surfaced on `Completion`)

---

## How was this tested?

- Unit tests for aggregation logic:
  - `UsageSummarySpec`
    - verifies add / merge semantics
    - cost accumulation only when present
    - immutability guarantees
- Minimal agent-flow integration test using a fake LLM client:
  - validates end-to-end wiring
  - ensures success-only accumulation
  - verifies correct request and cost totals

Commands run:
```bash
sbt core/test
# or
sbt "core/testOnly org.llm4s.agent.UsageSummarySpec"
```
## Checklist

- [x] I have read the Contributing Guide
- [x] PR is small and focused — one change, one reason
- [x] `sbt scalafmtAll` — code is formatted
- [x] `sbt +test` — tests pass on both Scala 2.13 and 3.x
- [x] New code includes tests
- [x] No unrelated changes included (branched cleanly and rebased as needed)
- [x] Commit messages explain the "why"

---

## Design notes

- Accumulation occurs **only on successful LLM completions**; failures and retries do not double-count.
- `continueConversation` naturally carries forward usage via immutable state copying.
- Handoff agents explicitly merge sub-agent `UsageSummary` back into the parent agent.
- JSON serialization is backward-compatible: missing `usageSummary` defaults safely.

---

## Review focus

- AgentState wiring
- Handoff merge logic
- Backward-compatible serialization

---

## Dependencies

- Depends on #512 (`Completion.estimatedCost`)

### CODE REVIEW

**Comment by VarshiniGunti** [comment]
Hi! 👋 This PR looks solid from a design and implementation perspective , the agent-level usage aggregation is well thought out and tests around UsageSummary and agent flow look good 👍

The red ❌ is coming from Codecov patch coverage, not test failures.

Right now coverage is 64% (target 80%), and the uncovered lines are mainly in the provider clients (OpenAI, DeepSeek, OpenRouter, Zai, Anthropic, Gemini, Ollama).Those files now include new logic for passing through estimatedCost, but there are no tests exercising those new code paths yet. So Codecov flags them as untested.

To fix this, you could add small provider-level tests that:
1. simulate completions with estimatedCost = Some(...)
2. verify that cost flows into Completion
3. ensure aggregation logic works when cost is present vs absent

No functional issue with the feature itself just missing coverage on the new provider wiring. Happy to help if you want to pair on adding those tests 🙂

File: modules/core/src/main/scala/org/llm4s/agent/UsageSummary.scala [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+object ModelUsage {
+  implicit val rw: RW[ModelUsage] = macroRW
+}
+
+case class UsageSummary(
+  requestCount: Long = 0L,
+  inputTokens: Long = 0L,
+  outputTokens: Long = 0L,
+  thinkingTokens: Long = 0L,
+  totalCost: Double = 0.0,
```
Comment (vim89) [inline modules/core/src/main/scala/org/llm4s/agent/UsageSummary.scala]: For accumulated money values, `Double` is risky because long-running agent loops can drift due to floating-point precision. Please use `BigDecimal` or scaled integer micros for stable accounting and serialization. Principle: financial aggregates must be deterministic and precision-safe.

File: modules/core/src/test/scala/org/llm4s/agent/AgentUsageIntegrationSpec.scala [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+import org.llm4s.llmconnect.model._
+import org.llm4s.toolapi.{ Schema, ToolFunction }
+import org.llm4s.toolapi.ToolRegistry
+import org.scalatest.flatspec.AnyFlatSpec
+import org.scalatest.matchers.should.Matchers
+import upickle.default._
+
+class AgentUsageIntegrationSpec extends AnyFlatSpec with Matchers {
+
+  "Agent" should "accumulate usage and cost into AgentState.usageSummary across multiple completions" in {
```
Comment (vim89) [inline modules/core/src/test/scala/org/llm4s/agent/AgentUsageIntegrationSpec.scala:12]: This spec only validates one happy path. Issue acceptance explicitly calls out handoff merge and continuation carry-forward; those branches are still unproven here. Please add tests for `continueConversation` and a handoff flow to prevent silent under/over-counting. Principle: critical state transitions need explicit branch coverage.

File: modules/core/src/main/scala/org/llm4s/agent/Agent.scala [hunk 3]
```diff
@@ -599,7 +612,11 @@ class Agent(client: LLMClient) {
     }
 
     // Run target agent from the prepared state
-    handoff.targetAgent.run(targetState, maxSteps, traceLogPath, debug)
+    handoff.targetAgent.run(targetState, maxSteps, traceLogPath, debug).map { targetFinalState =>
+      targetFinalState.copy(
+        usageSummary = sourceState.usageSummary.merge(targetFinalState.usageSummary)
```
Comment (vim89) [inline modules/core/src/main/scala/org/llm4s/agent/Agent.scala:695]: The merge logic here is core to billing correctness, but I do not see a direct test for nested handoff chains or repeated handoffs in one run. Please add one regression test to prove no double-count and no lost usage during delegation. Principle: critical aggregation code needs scenario coverage for edge transitions.

**Comment by gudiwadasruthi** [comment]
> Hi! 👋 This PR looks solid from a design and implementation perspective , the agent-level usage aggregation is well thought out and tests around UsageSummary and agent flow look good 👍
> 
> The red ❌ is coming from Codecov patch coverage, not test failures.
> 
> Right now coverage is 64% (target 80%), and the uncovered lines are mainly in the provider clients (OpenAI, DeepSeek, OpenRouter, Zai, Anthropic, Gemini, Ollama).Those files now include new logic for passing through estimatedCost, but there are no tests exercising those new code paths yet. So Codecov flags them as untested.
> 
> To fix this, you could add small provider-level tests that:
> 
> 1. simulate completions with estimatedCost = Some(...)
> 2. verify that cost flows into Completion
> 3. ensure aggregation logic works when cost is present vs absent
> 
> No functional issue with the feature itself just missing coverage on the new provider wiring. Happy to help if you want to pair on adding those tests 🙂

Thank you for your suggestions @VarshiniGunti  i will truely address them and make modifications according to them

**Comment by gudiwadasruthi** [comment]
@vim89 @rorygraves  Thanks for the coverage feedback.

After reviewing the Codecov report more closely, it looks like the patch coverage is being calculated across both #512 and #513 changes, since they currently live in the same branch. That includes provider-level modifications from #512 (cost exposure), which are not directly exercised by the agent-level tests added in this PR.

Because of that, patch coverage is lower than expected for this PR, even though the transition paths in AgentState (#513) are now explicitly covered.

To keep coverage clean and review scope focused, I’m considering splitting the work into two separate branches:

- #512 → cost exposure (provider + metrics changes)
- #513 → AgentState usage aggregation (building on #512)

This would allow patch coverage to reflect each feature independently and keep PR scope tighter.

Would you prefer that I restructure the branches accordingly before proceeding further?

**Comment by rorygraves** [comment]
@gudiwadasruthi Ignore the patch coverage - it doesn't work very well.  I think this is blocked behind #642 and will need to be rebased once that is cleanup and merged.

**Comment by gudiwadasruthi** [comment]
> @gudiwadasruthi Ignore the patch coverage - it doesn't work very well. I think this is blocked behind #642 and will need to be rebased once that is cleanup and merged.

okey @rorygraves let me know when it was merged then i will rebase it again

**Comment by gudiwadasruthi** [comment]
Hey @rorygraves @vim89 
## Update: Temporary Blocked by #656 

After rebasing this branch onto the latest `main`, I discovered that the recently merged `CohereClient` does not yet comply with the standardized `withMetrics` contract introduced in #512.

Specifically:
- `CohereClient` still uses the older `withMetrics` invocation style.
- It does not provide explicit `extractUsage` / `extractCost` lambdas.
- This results in compilation failures on current `main`.

Since #513 (agent-level usage aggregation) depends on provider-level usage and cost exposure being consistent, we have opened a separate issue:

👉 #656 — CohereClient does not implement updated withMetrics signature and cost tracking (post #512)

To keep scope clean and avoid mixing provider fixes into agent-level changes, we will:

1. Fix Cohere compliance in #656 .
2. Merge #655 into `main`.
3. Rebase #513 again on the updated `main`.
4. Proceed with final review and merge of #513.

This ensures:
- Clear separation of responsibilities (provider-level vs agent-level).
- No scope creep in #513.
- Clean CI and reproducible builds.
- Architectural consistency across all providers.

#513 remains ready from an agent-level perspective, but is temporarily blocked by provider-level compliance work in #656 .

**Comment by gudiwadasruthi** [comment]
Hey @rorygraves @vim89 
CI is currently failing because main does not compile due to the
CohereClient regression (tracked in #656).

Once #656 merges, I will rebase this branch onto updated main
and CI should turn green.
